name = "nextmatch"
main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"
build.command = "npm run build"
compatibility_date = "2021-11-12"

workers_dev = true
node_compat = true


[[ d1_databases ]]
binding = "DB"
database_name = "nextmatch"
database_id = "01236a62-a151-4bf7-b72c-07f07e834ee2"

